### ISSUE TITLE
Advanced Metrics - Any more in pipeline

### ISSUE THREAD

**Issue by pssguy** [keberwein/moneyball#3]
I'm pretty ignorant about how some of these are calculated and whether the base data allows you to do more but, for example, a recent article on [538](https://fivethirtyeight.com/features/why-everyone-should-love-adrian-beltre/?ex_cid=538twitter) about Adrian Beltre included RAR (Runs above Replavement) 

Your package has the somewhat similar RAA but does not allow me to directly replicate or expand on the 538 analyses

**Comment by keberwein** [comment]
I don't believe these data are capable of calculating RAR or WAR. Both of those metrics depend on data that isn't tracked here such as, park factors and specific base running and fielding events. We would really need play-by-play data for something like that. To make matters worse, those metrics aren't really standardized, and different people have different (and often closed-source) methods. Maybe take a look at Ben Baumer's [openWAR](https://github.com/beanumber/openWAR) package.

**Comment by pssguy** [comment]
The 538 article referenced baseball-reference and fangraphs, I believe, so I guess it is possible in theory

Thanks for suggestion I guess [baseballr](https://billpetti.github.io/baseballr/) might also be a potential source in future
